/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xepo;

import javax.swing.JOptionPane;

/**
 *
 * @author t3n1o12
 */
public class xepo extends javax.swing.JFrame {

    /**
     * Creates new form xepo
     */
    public xepo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Number sort");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("15");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("14");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("13");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("12");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("11");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("10");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("9");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("7");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("6");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("5");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setText("4");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setText("3");
        jButton13.setEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setText("2");
        jButton14.setEnabled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setText("1");
        jButton15.setEnabled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton16.setEnabled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setText("Start");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String name = JOptionPane.showInputDialog(null, "What is your name");
            this.setTitle(name);
            enable();
  
    }//GEN-LAST:event_jButton17ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jButton2.getText()==""){
            String crt = jButton1.getText();
            jButton1.setText("");
            jButton2.setText(crt);
        }
        else if(jButton4.getText()==""){
            String crt = jButton1.getText();
            jButton1.setText("");
            jButton4.setText(crt);
        }
   
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if(jButton15.getText()==""){
            String crt = jButton14.getText();
            jButton14.setText("");
            jButton15.setText(crt);
        }
        else if(jButton10.getText()==""){
            String crt = jButton14.getText();
            jButton14.setText("");
            jButton10.setText(crt);
        }
        else if(jButton13.getText()==""){
            String crt = jButton14.getText();
            jButton14.setText("");
            jButton13.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(jButton16.getText()==""){
            String crt = jButton12.getText();
            jButton12.setText("");
            jButton16.setText(crt);
        }
        else if(jButton8.getText()==""){
            String crt = jButton12.getText();
            jButton12.setText("");
            jButton8.setText(crt);
        }
        else if(jButton11.getText()==""){
            String crt = jButton12.getText();
            jButton12.setText("");
            jButton11.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(jButton12.getText()==""){
            String crt = jButton16.getText();
            jButton16.setText("");
            jButton12.setText(crt);
        }
        else if(jButton15.getText()==""){
            String crt = jButton16.getText();
            jButton16.setText("");
            jButton15.setText(crt);
        }
       
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(jButton11.getText()==""){
            String crt = jButton15.getText();
            jButton15.setText("");
            jButton11.setText(crt);
        }
        else if(jButton14.getText()==""){
            String crt = jButton15.getText();
            jButton15.setText("");
            jButton14.setText(crt);
        }
        else if(jButton16.getText()==""){
            String crt = jButton15.getText();
            jButton15.setText("");
            jButton16.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(jButton14.getText()==""){
            String crt = jButton13.getText();
            jButton13.setText("");
            jButton14.setText(crt);
        }
        else if(jButton9.getText()==""){
            String crt = jButton13.getText();
            jButton13.setText("");
            jButton9.setText(crt);
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(jButton7.getText()==""){
            String crt = jButton11.getText();
            jButton11.setText("");
            jButton7.setText(crt);
        }
        else if(jButton10.getText()==""){
            String crt = jButton11.getText();
            jButton11.setText("");
            jButton10.setText(crt);
        }
        else if(jButton12.getText()==""){
            String crt = jButton11.getText();
            jButton11.setText("");
            jButton12.setText(crt);
        }
        else if(jButton15.getText()==""){
            String crt = jButton11.getText();
            jButton11.setText("");
            jButton15.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(jButton4.getText()==""){
            String crt = jButton9.getText();
            jButton9.setText("");
            jButton4.setText(crt);
        }
        else if(jButton10.getText()==""){
            String crt = jButton9.getText();
            jButton9.setText("");
            jButton10.setText(crt);
        }
        else if(jButton13.getText()==""){
            String crt = jButton9.getText();
            jButton9.setText("");
            jButton13.setText(crt);
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(jButton6.getText()==""){
            String crt = jButton10.getText();
            jButton10.setText("");
            jButton6.setText(crt);
        }
        else if(jButton9.getText()==""){
            String crt = jButton10.getText();
            jButton10.setText("");
            jButton9.setText(crt);
        }
        else if(jButton11.getText()==""){
            String crt = jButton10.getText();
            jButton10.setText("");
            jButton11.setText(crt);
        }
        else if(jButton14.getText()==""){
            String crt = jButton10.getText();
            jButton10.setText("");
            jButton14.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(jButton5.getText()==""){
            String crt = jButton8.getText();
            jButton8.setText("");
            jButton5.setText(crt);
        }
        else if(jButton7.getText()==""){
            String crt = jButton8.getText();
            jButton8.setText("");
            jButton7.setText(crt);
        }
        else if(jButton12.getText()==""){
            String crt = jButton8.getText();
            jButton8.setText("");
            jButton12.setText(crt);
        }
    
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(jButton3.getText()==""){
            String crt = jButton7.getText();
            jButton7.setText("");
            jButton3.setText(crt);
        }
        else if(jButton6.getText()==""){
            String crt = jButton7.getText();
            jButton7.setText("");
            jButton6.setText(crt);
        }
        else if(jButton8.getText()==""){
            String crt = jButton7.getText();
            jButton7.setText("");
            jButton8.setText(crt);
        }
        else if(jButton11.getText()==""){
            String crt = jButton7.getText();
            jButton7.setText("");
            jButton11.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
        xep();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         if(jButton2.getText()==""){
            String crt = jButton6.getText();
            jButton6.setText("");
            jButton2.setText(crt);
        }
        else if(jButton4.getText()==""){
            String crt = jButton6.getText();
            jButton6.setText("");
            jButton4.setText(crt);
        }
        else if(jButton7.getText()==""){
            String crt = jButton6.getText();
            jButton6.setText("");
            jButton7.setText(crt);
        }
        else if(jButton10.getText()==""){
            String crt = jButton6.getText();
            jButton6.setText("");
            jButton10.setText(crt);
        }
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
         xep();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if(jButton1.getText()==""){
            String crt = jButton4.getText();
            jButton4.setText("");
            jButton1.setText(crt);
        }
        else if(jButton6.getText()==""){
            String crt = jButton4.getText();
            jButton4.setText("");
            jButton6.setText(crt);
        }
        else if(jButton9.getText()==""){
            String crt = jButton4.getText();
            jButton4.setText("");
            jButton9.setText(crt);
        }
       
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
         xep();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if(jButton3.getText()==""){
            String crt = jButton5.getText();
            jButton5.setText("");
            jButton3.setText(crt);
        }
        else if(jButton8.getText()==""){
            String crt = jButton5.getText();
            jButton5.setText("");
            jButton8.setText(crt);
        }
     
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
         xep();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if(jButton2.getText()==""){
            String crt = jButton3.getText();
            jButton3.setText("");
            jButton2.setText(crt);
        }
        else if(jButton5.getText()==""){
            String crt = jButton3.getText();
            jButton3.setText("");
            jButton5.setText(crt);
        }
        else if(jButton7.getText()==""){
            String crt = jButton3.getText();
            jButton3.setText("");
            jButton7.setText(crt);
        }
       
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
          xep();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(jButton1.getText()==""){
            String crt = jButton2.getText();
            jButton2.setText("");
            jButton1.setText(crt);
        }
        else if(jButton3.getText()==""){
            String crt = jButton2.getText();
            jButton2.setText("");
            jButton3.setText(crt);
        }
        else if(jButton6.getText()==""){
            String crt = jButton2.getText();
            jButton2.setText("");
            jButton6.setText(crt);
        }
    
        else{
            JOptionPane.showMessageDialog(null, "Click sai roi dai ca, click lai");
        }
         xep();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void hack(){
        jButton1.setText("1");
        jButton2.setText("2");
        jButton3.setText("3");
        jButton5.setText("4");
        jButton4.setText("5");
        jButton6.setText("6");
        jButton7.setText("7");
        jButton8.setText("8");
        jButton9.setText("9");
        jButton10.setText("10");
        jButton11.setText("11");
        jButton12.setText("12");
        jButton13.setText("13");
        jButton14.setText("14");
        jButton15.setText("");
        jButton16.setText("15");
    }
    public void enable(){
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton14.setEnabled(true);
        jButton15.setEnabled(true);
        jButton16.setEnabled(true);
    }
    public void xep(){
        if(
        jButton1.getText()=="1"&&
        jButton2.getText()=="2"&&
        jButton3.getText()=="3"&&
        jButton5.getText()=="4"&&
        jButton4.getText()=="5"&&
        jButton6.getText()=="6"&&
        jButton7.getText()=="7"&&
        jButton8.getText()=="8"&&
        jButton9.getText()=="9"&&
        jButton10.getText()=="10"&&
        jButton11.getText()=="11"&&
        jButton12.getText()=="12"&&
        jButton13.getText()=="13"&&
        jButton14.getText()=="14"&&
        jButton15.getText()=="15"&&
        jButton16.getText()==""){
            int reply= JOptionPane.showConfirmDialog(null,"Do you want to continue","Select option...",JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.NO_OPTION){
                System.exit(0);
            }
            else{
                rs();
            }
        }
    }
    public void rs(){
        jButton1.setText("15");
        jButton2.setText("14");
        jButton3.setText("13");
        jButton5.setText("12");
        jButton4.setText("11");
        jButton6.setText("10");
        jButton7.setText("9");
        jButton8.setText("8");
        jButton9.setText("7");
        jButton10.setText("6");
        jButton11.setText("5");
        jButton12.setText("4");
        jButton13.setText("3");
        jButton14.setText("2");
        jButton15.setText("1");
        jButton16.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xepo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
